import test from "node:test";
import assert from "node:assert/strict";
import {buildAiLogicExecutionPreviewContract as build} from "../src/scanner/ai_logic_execution_preview_contract.mjs";
const locks={productionRuntimeWiringAllowed:false,promotionExecutionAllowed:false,rollbackExecutionAllowed:false,brokerContactAllowed:false,orderPlacementAllowed:false,liveTradingAllowed:false,accountMutationAllowed:false,immutablePolicyMutationAllowed:false,thresholdMutationAllowed:false,sizingMutationAllowed:false,allocationMutationAllowed:false,gitMutationAllowed:false};
const c=(action="PROMOTION")=>({version:"ai_logic_operator_approval_consumption_record_v1",eligible:true,approvalRecordId:"ap1",nonce:"n1",action,decisionRecordId:"d1",candidateSourceHash:"c".repeat(64),currentSourceCommit:action==="PROMOTION"?"before":"after",targetSourceCommit:action==="PROMOTION"?"after":"before",...locks});
const common={immutableManifest:{ok:true,status:"IMMUTABLE_MANIFEST_VERIFIED"},decisionIdentity:{decisionRecordId:"d1",candidateSourceHash:"c".repeat(64)},knownGood:{valid:true,status:"KNOWN_GOOD_RECORD_VALID",sourceCommit:"before"},candidateTarget:{sourceCommit:"after"}};
test("builds promotion and rollback read-only previews with zero effects",()=>{for(const a of ["PROMOTION","ROLLBACK"]){const r=build({consumptionRecord:c(a),...common});assert.equal(r.eligible,true);assert.equal(r.previewOnly,true);assert.equal(r.gitEffects,"NONE");assert.equal(r.gitMutationAllowed,false)}});
test("fails closed on drift invalid manifest decision or opened authority",()=>{assert.equal(build({consumptionRecord:{...c(),currentSourceCommit:"x"},...common}).eligible,false);assert.equal(build({consumptionRecord:c(),...common,immutableManifest:{ok:false,status:"BAD"}}).eligible,false);assert.equal(build({consumptionRecord:c(),...common,decisionIdentity:{decisionRecordId:"x"}}).eligible,false);assert.equal(build({consumptionRecord:{...c(),gitMutationAllowed:true},...common}).eligible,false)});

test("binds candidate source hash",()=>{assert.equal(build({consumptionRecord:c(),...common}).candidateSourceHash,"c".repeat(64));assert.equal(build({consumptionRecord:c(),...common,decisionIdentity:{...common.decisionIdentity,candidateSourceHash:"d".repeat(64)}}).eligible,false)});
