import test from "node:test";
import assert from "node:assert/strict";
import {buildAiLogicShadowAssessmentPromotionDecision as run} from "../src/scanner/ai_logic_shadow_assessment_promotion_decision_adapter.mjs";
const L={productionRuntimeWiringAllowed:false,persistenceAllowed:false,promotionAllowed:false,promotionExecutionAllowed:false,rollbackExecutionAllowed:false,brokerContactAllowed:false,orderPlacementAllowed:false,liveTradingAllowed:false,accountMutationAllowed:false,immutablePolicyMutationAllowed:false,thresholdMutationAllowed:false,sizingMutationAllowed:false,allocationMutationAllowed:false,gitMutationAllowed:false};
const id={candidateId:"c1",candidatePath:"src/scanner/ai_logic_candidates/c1.mjs",candidateTopic:"classification_coverage",candidateSourceHash:"c".repeat(64),replayId:"r1",knownGoodRecordId:"kg1",sourceCommitBefore:"a".repeat(40),sourceCommitAfter:"b".repeat(40)};
function fx(){const acceptanceEvidence={version:"ai_logic_acceptance_evidence_store_v1",recordId:"ac1",immutableManifestStatus:"IMMUTABLE_MANIFEST_VERIFIED",localJsonlOnly:true,...id,...L};const knownGood={valid:true,status:"KNOWN_GOOD_RECORD_VALID",recordId:"kg1",sourceCommit:id.sourceCommitBefore,immutableManifestStatus:"IMMUTABLE_MANIFEST_VERIFIED",rollbackTargetIdentified:true,rollbackExecutable:false,promotionEligible:false,strategySwitchingAllowed:false,...L};const shadowAssessment={version:"ai_logic_shadow_probation_consumer_v1",accepted:true,status:"AI_LOGIC_SHADOW_PROBATION_ASSESSMENT_EVIDENCE",disposition:"ISOLATED_PROBATION_ASSESSMENT_EVIDENCE_ONLY",binding:{acceptanceRecordId:"ac1",...id},immutableManifestStatus:"IMMUTABLE_MANIFEST_VERIFIED",...L};const shadowAssessmentAdapter={version:"ai_logic_shadow_observation_assessment_adapter_v1",eligible:true,status:"AI_LOGIC_SHADOW_OBSERVATION_ASSESSMENT_READY",disposition:"SHADOW_ASSESSMENT_EVIDENCE_ONLY",assessmentCalled:true,sampleCount:1,shadowAssessment,...id,...L};return{explicitOperatorInvocation:true,acceptanceEvidence,knownGood,shadowAssessmentAdapter};}
test("builds exact promotion decision evidence from ready shadow assessment adapter",()=>{const r=run(fx());assert.equal(r.eligible,true);assert.equal(r.promotionDecisionCalled,true);assert.equal(r.promotionDecision.eligible,true);assert.equal(r.promotionDecision.status,"AI_LOGIC_PROMOTION_DECISION_EVIDENCE_READY");assert.equal(r.candidateSourceHash,id.candidateSourceHash);for(const [k,v] of Object.entries(L))assert.equal(r[k],v,k);});
test("requires explicit invocation and ready adapter",()=>{const a=fx();a.explicitOperatorInvocation=false;assert.equal(run(a).eligible,false);const b=fx();b.shadowAssessmentAdapter.status="HOLD";assert.equal(run(b).eligible,false);});
test("fails closed on adapter or assessment provenance drift",()=>{for(const k of ["candidateId","candidatePath","candidateTopic","candidateSourceHash","replayId","knownGoodRecordId","sourceCommitBefore","sourceCommitAfter"]){const a=fx();a.shadowAssessmentAdapter[k]="drift";assert.equal(run(a).eligible,false,k);const b=fx();b.shadowAssessmentAdapter.shadowAssessment.binding[k]="drift";assert.equal(run(b).eligible,false,`assessment ${k}`);}});
test("fails closed on open authority or invalid assessment",()=>{const a=fx();a.shadowAssessmentAdapter.orderPlacementAllowed=true;assert.equal(run(a).eligible,false);const b=fx();b.shadowAssessmentAdapter.shadowAssessment.accepted=false;assert.equal(run(b).eligible,false);});
test("preserves provenance on rejection",()=>{const x=fx();x.explicitOperatorInvocation=false;const r=run(x);assert.equal(r.candidateId,id.candidateId);assert.equal(r.candidatePath,id.candidatePath);assert.equal(r.candidateTopic,id.candidateTopic);assert.equal(r.promotionDecisionCalled,false);});
