import test from "node:test";
import assert from "node:assert/strict";
import mod,{VERSION,buildAiLogicOneShotNonruntimeInvocationContract as build} from "../src/scanner/ai_logic_one_shot_nonruntime_invocation_contract.mjs";
const B={productionRuntimeWiringAllowed:false,promotionExecutionAllowed:false,rollbackExecutionAllowed:false,brokerContactAllowed:false,orderPlacementAllowed:false,liveTradingAllowed:false,accountMutationAllowed:false,immutablePolicyMutationAllowed:false,thresholdMutationAllowed:false,sizingMutationAllowed:false,allocationMutationAllowed:false};
const G={...B,gitMutationAllowed:false};
const X={...G,runtimeActivationAllowed:false,pm2RestartAllowed:false,gitCheckoutAllowed:false,gitResetAllowed:false,gitRevertAllowed:false,gitMergeAllowed:false,gitCherryPickAllowed:false};
const D={...B,persistenceAllowed:false,promotionAllowed:false};
function fx(){const h="c".repeat(64),id={approvalRecordId:"ap1",nonce:"n1",action:"PROMOTION",decisionRecordId:"d1",candidateSourceHash:h,currentSourceCommit:"before",targetSourceCommit:"after"};return{operatorApproval:{version:"ai_logic_operator_approval_record_v1",valid:true,recordId:"ap1",nonce:"n1",action:"PROMOTION",decisionRecordId:"d1",acceptanceRecordId:"ac1",candidateId:"c1",knownGoodRecordId:"k1",replayId:"r1",sourceCommitBefore:"before",sourceCommitAfter:"after",candidateSourceHash:h,explicitlyApproved:true,oneShot:true,paperOnly:true,...G},consumptionStoreRecord:{version:"ai_logic_operator_approval_consumption_store_v1",exactlyOnce:true,paperOnly:true,localJsonlOnly:true,...id,...G},decisionEvidence:{version:"ai_logic_promotion_decision_evidence_store_v1",recordId:"d1",acceptanceRecordId:"ac1",candidateId:"c1",knownGoodRecordId:"k1",replayId:"r1",sourceCommitBefore:"before",sourceCommitAfter:"after",candidateSourceHash:h,immutableManifestStatus:"IMMUTABLE_MANIFEST_VERIFIED",localJsonlOnly:true,...D},orchestratorContract:{version:"ai_logic_local_integration_orchestrator_contract_v1",eligible:true,localCandidateSourceApplySeamReady:true,...id,...X},boundaryEvidence:{version:"ai_logic_execution_boundary_gate_v1",eligible:true,applyEligibilityOnly:true,readOnly:true,evidenceOnly:true,paperOnly:true,...id,...G},targetPath:"src/scanner/ai_logic_candidates/example.mjs",expectedPreimageHash:"d".repeat(64),operationId:"op-ready-001"}}
test("exports exact version and builder",()=>{assert.equal(VERSION,"ai_logic_one_shot_nonruntime_invocation_contract_v1");assert.equal(mod.VERSION,VERSION);assert.equal(typeof build,"function")});
test("missing inputs fail closed",()=>{const x=build({});assert.equal(x.eligible,false);assert.ok(x.reasons.length>0);assert.equal(x.runtimeWiringAllowed,false);assert.equal(x.candidateRootBootstrapAllowed,false)});
test("promotion ready path is one shot local only",()=>{const x=build(fx());assert.equal(x.eligible,true);assert.equal(x.status,"AI_LOGIC_ONE_SHOT_NONRUNTIME_INVOCATION_READY");assert.equal(x.operatorInvokedLocalOnly,true);assert.equal(x.runtimeActivationAllowed,false);assert.equal(x.gitMutationAllowed,false)});

test("promotion fails closed on authority identity and decision drift",()=>{const cases=[x=>x.consumptionStoreRecord.nonce="x",x=>x.boundaryEvidence.targetSourceCommit="drift",x=>x.decisionEvidence.candidateSourceHash="e".repeat(64),x=>x.decisionEvidence.promotionExecutionAllowed=true,x=>x.orchestratorContract.currentSourceCommit="drift"];for(const m of cases){const x=fx();m(x);assert.equal(build(x).eligible,false)}});

test("rollback ready path reverses source commits and remains local only",()=>{const x=fx();x.operatorApproval={...x.operatorApproval,action:"ROLLBACK",acceptanceRecordId:null,sourceCommitBefore:"before",sourceCommitAfter:"after"};x.decisionEvidence={...x.decisionEvidence,version:"ai_logic_rollback_decision_evidence_store_v1",promotionDecisionRecordId:"pd1"};x.orchestratorContract={...x.orchestratorContract,action:"ROLLBACK",currentSourceCommit:"after",targetSourceCommit:"before"};x.boundaryEvidence={...x.boundaryEvidence,action:"ROLLBACK",currentSourceCommit:"after",targetSourceCommit:"before"};x.consumptionStoreRecord={...x.consumptionStoreRecord,action:"ROLLBACK",currentSourceCommit:"after",targetSourceCommit:"before"};const r=build(x);assert.equal(r.eligible,true);assert.equal(r.action,"ROLLBACK");assert.equal(r.currentSourceCommit,"after");assert.equal(r.targetSourceCommit,"before");assert.equal(r.runtimeActivationAllowed,false);assert.equal(r.gitMutationAllowed,false)});


test("operator paperOnly and boundary evidence flags fail closed",()=>{for(const f of [x=>x.operatorApproval.paperOnly=false,x=>x.boundaryEvidence.readOnly=false,x=>x.boundaryEvidence.evidenceOnly=false]){const x=fx();f(x);assert.equal(build(x).eligible,false)}});
test("decision version consumption binding and invocation identifiers fail closed",()=>{for(const f of [x=>x.decisionEvidence.version="ai_logic_rollback_decision_evidence_store_v1",x=>x.consumptionStoreRecord.approvalRecordId="other",x=>x.targetPath="../bad.mjs",x=>x.expectedPreimageHash="bad",x=>x.operationId="short"]){const x=fx();f(x);assert.equal(build(x).eligible,false)}});
