import test from "node:test";
import assert from "node:assert/strict";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import { buildAiLogicOperatorApprovalRecord as build, appendAiLogicOperatorApprovalRecord as append } from "../src/scanner/ai_logic_operator_approval_record.mjs";
const base=(action="PROMOTION")=>({action,decisionRecordId:"d1",acceptanceRecordId:action==="PROMOTION"?"a1":null,candidateId:"c1",knownGoodRecordId:"k1",replayId:"r1",sourceCommitBefore:"before",sourceCommitAfter:"after",nonce:"n1",explicitlyApproved:true,oneShot:true,issuedAt:"2026-09-02T23:00:00Z",expiresAt:"2026-09-03T00:00:00Z",paperOnly:true,noLiveTradingAcknowledged:true,noImmutablePolicyMutationAcknowledged:true});
test("builds deterministic promotion and rollback approvals with all authority locked",()=>{for(const a of ["PROMOTION","ROLLBACK"]){const r=build(base(a));assert.equal(r.valid,true);assert.equal(r.gitMutationAllowed,false);assert.equal(r.promotionExecutionAllowed,false);assert.equal(r.rollbackExecutionAllowed,false)}});
test("fails closed on missing approval nonce expiry or identity",()=>{for(const patch of [{explicitlyApproved:false},{nonce:""},{expiresAt:"2026-09-02T22:00:00Z"},{candidateId:""}]) assert.equal(build({...base(),...patch}).valid,false)});
test("persists private local jsonl once and deduplicates",()=>{const d=fs.mkdtempSync(path.join(os.tmpdir(),"a54r9-"));const f=path.join(d,"x","a.jsonl");const r=build(base());assert.equal(append(r,f).appended,true);assert.equal(append(r,f).appended,false);assert.equal(fs.statSync(f).mode&0o777,0o600);assert.equal(fs.statSync(path.dirname(f)).mode&0o777,0o700)});
