import test from "node:test";
import assert from "node:assert/strict";
import {buildAiLogicShadowObservationProbationEvidenceBridge as run} from "../src/scanner/ai_logic_shadow_observation_probation_evidence_bridge.mjs";
const L={productionRuntimeWiringAllowed:false,persistenceAllowed:false,promotionAllowed:false,rollbackExecutionAllowed:false,brokerContactAllowed:false,orderPlacementAllowed:false,liveTradingAllowed:false,accountMutationAllowed:false,immutablePolicyMutationAllowed:false,thresholdMutationAllowed:false,sizingMutationAllowed:false,allocationMutationAllowed:false,gitMutationAllowed:false};
const id={candidateId:"c1",candidatePath:"src/scanner/ai_logic_candidates/c1.mjs",candidateTopic:"classification_coverage",candidateSourceHash:"c".repeat(64),replayId:"r1",knownGoodRecordId:"kg1",sourceCommitBefore:"a".repeat(40),sourceCommitAfter:"b".repeat(40)};
function fx(){const acceptance={version:"ai_logic_acceptance_evidence_store_v1",recordId:"ac1",immutableManifestStatus:"IMMUTABLE_MANIFEST_VERIFIED",localJsonlOnly:true,...id,...L};const shadowEntryEvidence={version:"ai_logic_shadow_entry_binding_v1",eligible:true,status:"AI_LOGIC_SHADOW_ENTRY_BINDING_VALID",disposition:"SHADOW_ENTRY_EVIDENCE_ONLY",binding:{...id},...L};const knownGood={valid:true,status:"KNOWN_GOOD_RECORD_VALID",recordId:"kg1",sourceCommit:id.sourceCommitBefore,immutableManifestStatus:"IMMUTABLE_MANIFEST_VERIFIED",...L};const shadowObservations={version:"ai_logic_shadow_observation_producer_v1",eligible:true,status:"AI_LOGIC_SHADOW_OBSERVATIONS_READY",disposition:"ISOLATED_SHADOW_OBSERVATIONS_ONLY",observations:[{sampleId:"s1",baseline:"WAIT",candidate:"ENTER",changed:true}],sampleCount:1,baselineEvaluatorCalled:true,candidateEvaluatorCalled:true,...id,...L};return{explicitOperatorInvocation:true,acceptanceEvidence:acceptance,shadowEntryEvidence,knownGood,shadowObservations};}
test("bridges exact isolated observations into complete probation evidence",()=>{const r=run(fx());assert.equal(r.eligible,true);assert.equal(r.probationBuilderCalled,true);assert.equal(r.probationEvidence.complete,true);assert.equal(r.probationEvidence.sampleCount,1);assert.equal(r.candidateSourceHash,id.candidateSourceHash);for(const [k,v] of Object.entries(L))assert.equal(r[k],v,k);});
test("requires explicit invocation and ready observations",()=>{const a=fx();a.explicitOperatorInvocation=false;assert.equal(run(a).eligible,false);const b=fx();b.shadowObservations.status="HOLD";assert.equal(run(b).eligible,false);});
test("fails closed on observation provenance drift",()=>{for(const k of ["candidateId","candidatePath","candidateTopic","candidateSourceHash","replayId","knownGoodRecordId","sourceCommitBefore","sourceCommitAfter"]){const x=fx();x.shadowObservations[k]="drift";assert.equal(run(x).eligible,false,k);}});
test("fails closed on sample count mismatch or open authority",()=>{const a=fx();a.shadowObservations.sampleCount=2;assert.equal(run(a).eligible,false);const b=fx();b.shadowObservations.orderPlacementAllowed=true;assert.equal(run(b).eligible,false);});
test("preserves provenance on rejection",()=>{const x=fx();x.explicitOperatorInvocation=false;const r=run(x);assert.equal(r.candidateId,id.candidateId);assert.equal(r.candidatePath,id.candidatePath);assert.equal(r.candidateTopic,id.candidateTopic);assert.equal(r.probationBuilderCalled,false);});
