import test from"node:test";import assert from"node:assert/strict";import{runAiLogicOneShotNonruntimeInvocation as run}from"../src/scanner/ai_logic_one_shot_nonruntime_invocation_runner.mjs";const K={runtimeActivationAllowed:false,pm2RestartAllowed:false,productionRuntimeWiringAllowed:false,promotionExecutionAllowed:false,rollbackExecutionAllowed:false,brokerContactAllowed:false,orderPlacementAllowed:false,liveTradingAllowed:false,accountMutationAllowed:false,immutablePolicyMutationAllowed:false,thresholdMutationAllowed:false,sizingMutationAllowed:false,allocationMutationAllowed:false,gitMutationAllowed:false,gitCheckoutAllowed:false,gitResetAllowed:false,gitRevertAllowed:false,gitMergeAllowed:false,gitCherryPickAllowed:false},F={approvalRecordId:"a",nonce:"n",action:"PROMOTION",decisionRecordId:"d",candidateSourceHash:"c".repeat(64),candidatePath:"src/scanner/ai_logic_candidates/x.mjs",candidateTopic:"evidence_interpretation",currentSourceCommit:"b",targetSourceCommit:"t"},I=p=>({version:"ai_logic_one_shot_nonruntime_invocation_contract_v1",eligible:true,operatorInvokedLocalOnly:true,runtimeWiringAllowed:false,knownGoodRecordId:"kg",knownGoodSourceCommit:"b",targetPath:"src/scanner/ai_logic_candidates/x.mjs",expectedPreimageHash:"e".repeat(64),operationId:"op-ready-1",...K,...F, ...p}),C=p=>({version:"ai_logic_operator_approval_consumption_record_v1",eligible:true,status:"AI_LOGIC_OPERATOR_APPROVAL_CONSUMPTION_READY",disposition:"ONE_SHOT_CONSUMPTION_EVIDENCE_ONLY",oneShot:true,atomicConsumptionRequired:true,exactlyOnceRequired:true,auditEvidenceRequired:true,paperOnly:true,...K,...F,...p}),X=i=>({orchestratorContract:{version:"ai_logic_local_integration_orchestrator_contract_v1",eligible:true,localCandidateSourceApplySeamReady:true,knownGoodRecordId:i.knownGoodRecordId,knownGoodSourceCommit:i.knownGoodSourceCommit,status:"AI_LOGIC_LOCAL_INTEGRATION_ORCHESTRATOR_READY",disposition:"EXPLICIT_LOCAL_CANDIDATE_SOURCE_APPLY_SEAM_ONLY",localCandidateFilesystemMutationScope:"ALLOWLISTED_AI_LOGIC_CANDIDATE_SOURCE_ONLY",...K,...F},atomicExecutorInput:{boundaryEvidence:{version:"ai_logic_execution_boundary_gate_v1",eligible:true,applyEligibilityOnly:true,readOnly:true,evidenceOnly:true,paperOnly:true,...K,...F},targetPath:i.targetPath,expectedPreimageHash:i.expectedPreimageHash,operationId:i.operationId}});
test("block",()=>{let n=0,r=run({invocationContract:I({eligible:false}),consumptionRecord:C(),appendConsumption:()=>n++,executeSeam:()=>n++});assert.equal(n,0);assert.equal(r.consumed,false)});
test("order",()=>{let q=[],r=run({invocationContract:I(),consumptionRecord:C(),executionInput:X(I()),appendConsumption:x=>(q.push("c"),{appended:true,record:{...x}}),executeSeam:()=>{q.push("e");return{executed:true,applied:true}}});assert.deepEqual(q,["c","e"]);assert.equal(r.consumed,true);assert.equal(r.applied,true)});
test("replay",()=>{let n=0,r=run({invocationContract:I(),consumptionRecord:C(),executionInput:X(I()),appendConsumption:()=>({appended:false,reason:"ALREADY_CONSUMED"}),executeSeam:()=>n++});assert.equal(n,0);assert.equal(r.consumed,true);assert.equal(r.automaticRetryAllowed,false)});
test("fail",()=>{let r=run({invocationContract:I(),consumptionRecord:C(),executionInput:X(I()),appendConsumption:x=>({appended:true,record:{...x}}),executeSeam:()=>{throw Error("x")}});assert.equal(r.consumed,true);assert.equal(r.executed,false);assert.equal(r.automaticRetryAllowed,false)});
test("execution input drift blocks before consumption",()=>{let n=0,i=I({targetPath:"src/scanner/ai_logic_candidates/x.mjs",expectedPreimageHash:"e".repeat(64),operationId:"op-ready-1"}),e={orchestratorContract:{...F},atomicExecutorInput:{boundaryEvidence:{...F},targetPath:i.targetPath,expectedPreimageHash:i.expectedPreimageHash,operationId:"drift-op"}};let r=run({invocationContract:i,consumptionRecord:C(),executionInput:e,appendConsumption:()=>n++,executeSeam:()=>n++});assert.equal(n,0);assert.equal(r.consumed,false)});
test("stored consumption binding drift stays consumed and does not execute",()=>{let n=0,i=I({targetPath:"src/scanner/ai_logic_candidates/x.mjs",expectedPreimageHash:"e".repeat(64),operationId:"op-ready-1"}),e=X(i);let r=run({invocationContract:i,consumptionRecord:C(),executionInput:e,appendConsumption:x=>({appended:true,record:{...x,nonce:"drift"}}),executeSeam:()=>n++});assert.equal(n,0);assert.equal(r.consumed,true);assert.equal(r.status,"ONE_SHOT_CONSUMPTION_STORE_BINDING_FAILED")});


test("known-good preconsumption drift blocks before consumption",()=>{for(const f of [(i,e)=>i.knownGoodRecordId="drift",(i,e)=>e.orchestratorContract.knownGoodSourceCommit="drift"]){let n=0,i=I(),e=X(i);f(i,e);const r=run({invocationContract:i,consumptionRecord:C(),executionInput:e,appendConsumption:()=>n++,executeSeam:()=>n++});assert.equal(n,0);assert.equal(r.consumed,false);assert.ok(r.reasons.includes("KNOWN_GOOD_BINDING_PRECONSUMPTION_INVALID"))}});

test("preconsumption authority and readiness drift blocks before consumption",()=>{const cases=[(i,e)=>i.gitMutationAllowed=true,(i,e)=>e.orchestratorContract.pm2RestartAllowed=true,(i,e)=>e.atomicExecutorInput.boundaryEvidence.gitMutationAllowed=true,(i,e)=>e.orchestratorContract.status="DRIFT",(i,e)=>e.atomicExecutorInput.boundaryEvidence.readOnly=false];for(const f of cases){let n=0,i=I(),e=X(i);f(i,e);const r=run({invocationContract:i,consumptionRecord:C(),executionInput:e,appendConsumption:()=>n++,executeSeam:()=>n++});assert.equal(n,0);assert.equal(r.consumed,false);assert.equal(r.executed,false)}});


test("consumption canonical prevalidation drift blocks before append",()=>{const cases=[c=>c.status="DRIFT",c=>c.disposition="DRIFT",c=>c.oneShot=false,c=>c.atomicConsumptionRequired=false,c=>c.exactlyOnceRequired=false,c=>c.auditEvidenceRequired=false,c=>c.paperOnly=false,c=>c.gitMutationAllowed=true,c=>c.liveTradingAllowed=true];for(const f of cases){let n=0,i=I(),c=C(),e=X(i);f(c);const r=run({invocationContract:i,consumptionRecord:c,executionInput:e,appendConsumption:()=>n++,executeSeam:()=>n++});assert.equal(n,0);assert.equal(r.consumed,false);assert.equal(r.executed,false)}});


test("injected seam authority output is sanitized closed",()=>{let i=I(),e=X(i),r=run({invocationContract:i,consumptionRecord:C(),executionInput:e,appendConsumption:x=>({appended:true,record:{...x}}),executeSeam:()=>({executed:true,applied:true,liveTradingAllowed:true,pm2RestartAllowed:true,gitMutationAllowed:true})});assert.equal(r.consumed,true);assert.equal(r.executed,true);assert.equal(r.applied,true);for(const k of Object.keys(K))assert.equal(r[k],false,k);assert.equal(r.automaticRetryAllowed,false)});

test("invocation receipts preserve canonical candidate provenance across blocked and failure outcomes",()=>{const assertP=r=>{assert.equal(r.candidateSourceHash,F.candidateSourceHash);assert.equal(r.candidatePath,F.candidatePath);assert.equal(r.candidateTopic,F.candidateTopic)};let i=I(),e=X(i);assertP(run({invocationContract:{...i,eligible:false},consumptionRecord:C(),executionInput:e,appendConsumption:()=>{throw Error("should-not-run")},executeSeam:()=>{throw Error("should-not-run")}}));assertP(run({invocationContract:i,consumptionRecord:C(),executionInput:e,appendConsumption:()=>{throw Error("consume")},executeSeam:()=>({})}));assertP(run({invocationContract:i,consumptionRecord:C(),executionInput:e,appendConsumption:()=>({appended:false,reason:"ALREADY_CONSUMED"}),executeSeam:()=>({})}));assertP(run({invocationContract:i,consumptionRecord:C(),executionInput:e,appendConsumption:x=>({appended:true,record:{...x,nonce:"drift"}}),executeSeam:()=>({})}));assertP(run({invocationContract:i,consumptionRecord:C(),executionInput:e,appendConsumption:x=>({appended:true,record:{...x}}),executeSeam:()=>{throw Error("execution")}}))});
