import test from"node:test";
import assert from"node:assert/strict";
import crypto from"node:crypto";
import{buildAiLogicExecutionBoundaryGate as b}from"../src/scanner/ai_logic_execution_boundary_gate.mjs";
const H=s=>crypto.createHash("sha256").update(s).digest("hex");
const L={productionRuntimeWiringAllowed:false,promotionExecutionAllowed:false,rollbackExecutionAllowed:false,brokerContactAllowed:false,orderPlacementAllowed:false,liveTradingAllowed:false,accountMutationAllowed:false,immutablePolicyMutationAllowed:false,thresholdMutationAllowed:false,sizingMutationAllowed:false,allocationMutationAllowed:false,gitMutationAllowed:false};
function fx(){const artifact="candidate-v1",hash=H(artifact),id={approvalRecordId:"ap1",nonce:"n1",action:"PROMOTION",decisionRecordId:"d1",candidateSourceHash:hash,currentSourceCommit:"before",targetSourceCommit:"after"};return{executionIntentAcknowledgement:{version:"ai_logic_execution_intent_acknowledgement_contract_v1",eligible:true,readOnly:true,evidenceOnly:true,acknowledgementOnly:true,paperOnly:true,...id,...L},consumptionRecord:{version:"ai_logic_operator_approval_consumption_store_v1",exactlyOnce:true,paperOnly:true,...id,...L},immutableManifest:{ok:true,status:"IMMUTABLE_MANIFEST_VERIFIED"},candidateArtifact:artifact,currentHead:"before",changedPaths:["src/scanner/ai_logic_candidates/example.mjs"],candidateTopic:"evidence_interpretation",now:"2026-09-05T01:50:00Z"}}
test("emits apply eligibility evidence only with all locks closed",()=>{const r=b(fx());assert.equal(r.eligible,true);assert.equal(r.applyEligibilityOnly,true);assert.equal(r.promotionExecutionAllowed,false);assert.equal(r.gitMutationAllowed,false);assert.equal(r.candidateArtifactHash,r.candidateSourceHash)});
test("fails closed on identity source hash head manifest path or authority drift",()=>{const cases=[x=>x.consumptionRecord.nonce="x",x=>x.candidateArtifact="tampered",x=>x.currentHead="drift",x=>x.immutableManifest={ok:false,status:"BAD"},x=>x.changedPaths=["src/server.js"],x=>x.executionIntentAcknowledgement.gitMutationAllowed=true];for(const m of cases){const x=fx();m(x);assert.equal(b(x).eligible,false)}});
test("requires changed paths and valid time evidence",()=>{let x=fx();x.changedPaths=[];assert.equal(b(x).eligible,false);x=fx();x.now="bad";assert.equal(b(x).eligible,false)});
