import test from "node:test";
import assert from "node:assert/strict";
import {buildAiLogicShadowObservationAssessment as run} from "../src/scanner/ai_logic_shadow_observation_assessment_adapter.mjs";
const L={productionRuntimeWiringAllowed:false,persistenceAllowed:false,promotionAllowed:false,rollbackExecutionAllowed:false,brokerContactAllowed:false,orderPlacementAllowed:false,liveTradingAllowed:false,accountMutationAllowed:false,immutablePolicyMutationAllowed:false,thresholdMutationAllowed:false,sizingMutationAllowed:false,allocationMutationAllowed:false,gitMutationAllowed:false};
const id={candidateId:"c1",candidatePath:"src/scanner/ai_logic_candidates/c1.mjs",candidateTopic:"classification_coverage",candidateSourceHash:"c".repeat(64),replayId:"r1",knownGoodRecordId:"kg1",sourceCommitBefore:"a".repeat(40),sourceCommitAfter:"b".repeat(40)};
function fx(){const acceptanceEvidence={version:"ai_logic_acceptance_evidence_store_v1",recordId:"ac1",immutableManifestStatus:"IMMUTABLE_MANIFEST_VERIFIED",localJsonlOnly:true,...id,...L};const shadowEntryEvidence={version:"ai_logic_shadow_entry_binding_v1",eligible:true,status:"AI_LOGIC_SHADOW_ENTRY_BINDING_VALID",disposition:"SHADOW_ENTRY_EVIDENCE_ONLY",binding:{...id},...L};const knownGood={valid:true,status:"KNOWN_GOOD_RECORD_VALID",recordId:"kg1",sourceCommit:id.sourceCommitBefore,immutableManifestStatus:"IMMUTABLE_MANIFEST_VERIFIED",rollbackTargetIdentified:true,rollbackExecutable:false,promotionEligible:false,strategySwitchingAllowed:false,...L};const probationEvidence={complete:true,status:"SHADOW_PROBATION_EVIDENCE_COMPLETE",sampleCount:1,acceptanceRecordId:"ac1",immutableManifestStatus:"IMMUTABLE_MANIFEST_VERIFIED",...id,...L};const probationBridge={version:"ai_logic_shadow_observation_probation_evidence_bridge_v1",eligible:true,status:"AI_LOGIC_SHADOW_OBSERVATION_PROBATION_BRIDGE_READY",disposition:"SHADOW_PROBATION_EVIDENCE_ONLY",probationBuilderCalled:true,sampleCount:1,probationEvidence,...id,...L};return{explicitOperatorInvocation:true,acceptanceEvidence,shadowEntryEvidence,knownGood,probationBridge};}
test("builds exact shadow assessment evidence from ready probation bridge",()=>{const r=run(fx());assert.equal(r.eligible,true);assert.equal(r.assessmentCalled,true);assert.equal(r.shadowAssessment.accepted,true);assert.equal(r.shadowAssessment.status,"AI_LOGIC_SHADOW_PROBATION_ASSESSMENT_EVIDENCE");assert.equal(r.candidateSourceHash,id.candidateSourceHash);for(const [k,v] of Object.entries(L))assert.equal(r[k],v,k);});
test("requires explicit invocation and ready bridge",()=>{const a=fx();a.explicitOperatorInvocation=false;assert.equal(run(a).eligible,false);const b=fx();b.probationBridge.status="HOLD";assert.equal(run(b).eligible,false);});
test("fails closed on bridge provenance drift",()=>{for(const k of ["candidateId","candidatePath","candidateTopic","candidateSourceHash","replayId","knownGoodRecordId","sourceCommitBefore","sourceCommitAfter"]){const x=fx();x.probationBridge[k]="drift";assert.equal(run(x).eligible,false,k);}});
test("fails closed on open authority or invalid probation evidence",()=>{const a=fx();a.probationBridge.orderPlacementAllowed=true;assert.equal(run(a).eligible,false);const b=fx();b.probationBridge.probationEvidence.status="HOLD";assert.equal(run(b).eligible,false);});
test("preserves provenance on rejection",()=>{const x=fx();x.explicitOperatorInvocation=false;const r=run(x);assert.equal(r.candidateId,id.candidateId);assert.equal(r.candidatePath,id.candidatePath);assert.equal(r.candidateTopic,id.candidateTopic);assert.equal(r.assessmentCalled,false);});
