import test from"node:test";
import assert from"node:assert/strict";
import{buildAiLogicExecutionIntentEvidence as b}from"../src/scanner/ai_logic_execution_intent_evidence_contract.mjs";
const L={productionRuntimeWiringAllowed:false,promotionExecutionAllowed:false,rollbackExecutionAllowed:false,brokerContactAllowed:false,orderPlacementAllowed:false,liveTradingAllowed:false,accountMutationAllowed:false,immutablePolicyMutationAllowed:false,thresholdMutationAllowed:false,sizingMutationAllowed:false,allocationMutationAllowed:false,gitMutationAllowed:false};
function plan(action="PROMOTION"){const cur=action==="PROMOTION"?"before":"after",tar=action==="PROMOTION"?"after":"before";return{version:"ai_logic_execution_plan_v1",eligible:true,planOnly:true,readOnly:true,paperOnly:true,approvalRecordId:"ap1",nonce:"n1",action,decisionRecordId:"d1",candidateSourceHash:"c".repeat(64),currentSourceCommit:cur,targetSourceCommit:tar,executionSideEffects:"NONE",gitEffects:"NONE",postconditions:{executionSideEffects:"NONE",gitEffects:"NONE",runtimeIntegration:"NONE"},...L}}
test("builds promotion and rollback readonly intent evidence",()=>{for(const a of["PROMOTION","ROLLBACK"]){const r=b({executionPlan:plan(a)});assert.equal(r.eligible,true);assert.equal(r.readOnly,true);assert.equal(r.evidenceOnly,true);assert.equal(r.executionIntentOnly,true);assert.equal(r.executionSideEffects,"NONE");assert.equal(r.gitEffects,"NONE");assert.equal(r.runtimeIntegration,"NONE");assert.deepEqual(r.exactSourceTransition,{from:r.currentSourceCommit,to:r.targetSourceCommit});assert.equal(Object.isFrozen(r),true);assert.equal(Object.isFrozen(r.reasons),true);assert.equal(Object.isFrozen(r.exactSourceTransition),true);assert.equal(r.promotionExecutionAllowed,false);assert.equal(r.rollbackExecutionAllowed,false);assert.equal(r.gitMutationAllowed,false)}});
test("fails closed on invalid plan opened authority or nonzero effects",()=>{const cases=[p=>p.version="bad",p=>p.eligible=false,p=>p.paperOnly=false,p=>p.gitMutationAllowed=true,p=>p.postconditions.executionSideEffects="WRITE",p=>p.postconditions.gitEffects="WRITE",p=>p.targetSourceCommit=p.currentSourceCommit,p=>p.executionSideEffects="MUTATION",p=>p.gitEffects="WRITE",p=>p.postconditions.runtimeIntegration="ACTIVE",p=>p.targetSourceCommit=""];for(const m of cases){const p=plan();m(p);assert.equal(b({executionPlan:p}).eligible,false)}});

test("requires candidate source hash",()=>{const p=plan();p.candidateSourceHash="";assert.equal(b({executionPlan:p}).eligible,false)});
