import test from "node:test";
import assert from "node:assert/strict";
import {buildAiManualAdjustmentWeeklyReportEmail,deliverAiManualAdjustmentWeeklyReportEmail} from "../src/scanner/ai_manual_adjustment_weekly_report_email_delivery.mjs";
const report={generatedAt:"2026-09-01T16:00:00.000Z",periodStart:"2026-08-25T16:00:00.000Z",periodEnd:"2026-09-01T16:00:00.000Z",recommendationCount:2,lifecycleStatus:"AWAITING_MANUAL_REVIEW"};
const pdf={filename:"GeminiScanner-Weekly-AI-Adjustment-Recommendations.pdf",contentType:"application/pdf",buffer:Buffer.from("%PDF-1.4 test")};
test("weekly AI email message remains proposal only",()=>{const m=buildAiManualAdjustmentWeeklyReportEmail({report,recipient:"admin@example.test",sender:"sender@example.test"});assert.match(m.subject,/\(2\)/);assert.match(m.text,/backtesting and operator approval/i);assert.match(m.text,/PROPOSAL ONLY/);});
test("delivery fail-closes without explicit authorization",async()=>{let n=0;const r=await deliverAiManualAdjustmentWeeklyReportEmail({report,pdf},{env:{CUSTOMER_EMAIL_PROVIDER:"resend",RESEND_API_KEY:"secret",CUSTOMER_EMAIL_FROM:"sender@example.test",GS_WATCHDOG_ALERT_RECIPIENT:"admin@example.test"},fetchImpl:async()=>{n++;throw Error("no")}});assert.equal(r.delivered,false);assert.equal(r.attempted,false);assert.equal(r.reason,"weekly_ai_report_email_send_not_authorized");assert.equal(n,0);});
test("authorized delivery contains provider exception without exposing configuration",async()=>{const r=await deliverAiManualAdjustmentWeeklyReportEmail({report,pdf},{env:{GS_AI_WEEKLY_REPORT_EMAIL_SEND_AUTHORIZED:"true",CUSTOMER_EMAIL_PROVIDER:"resend",RESEND_API_KEY:"secret-test-key",CUSTOMER_EMAIL_FROM:"sender@example.test",GS_WATCHDOG_ALERT_RECIPIENT:"admin@example.test"},fetchImpl:async()=>{throw Error("network-down")}});assert.deepEqual(r,{delivered:false,attempted:true,provider:"resend",statusCode:null,reason:"resend_delivery_error"});assert.doesNotMatch(JSON.stringify(r),/secret-test-key|admin@example\.test|sender@example\.test|network-down/);});
test("authorized delivery attaches PDF",async()=>{let q;const r=await deliverAiManualAdjustmentWeeklyReportEmail({report,pdf},{env:{GS_AI_WEEKLY_REPORT_EMAIL_SEND_AUTHORIZED:"true",CUSTOMER_EMAIL_PROVIDER:"resend",RESEND_API_KEY:"secret-test-key",CUSTOMER_EMAIL_FROM:"sender@example.test",GS_WATCHDOG_ALERT_RECIPIENT:"admin@example.test"},fetchImpl:async(url,options)=>{q={url,options};return{ok:true,status:200,json:async()=>({id:"weekly-1"})}}});assert.equal(r.delivered,true);const b=JSON.parse(q.options.body);assert.equal(b.to[0],"admin@example.test");assert.equal(b.attachments[0].content,pdf.buffer.toString("base64"));assert.doesNotMatch(JSON.stringify(r),/secret-test-key|admin@example\.test|sender@example\.test/);});
