import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import os from 'node:os';import path from 'node:path'
import { PaperAutoExecutionLifecycleStore } from '../src/scanner/paper_auto_execution_lifecycle_store.mjs'
import { createPaperAutoExecutionContinuityRuntime } from '../src/scanner/paper_auto_execution_continuity_runtime.mjs'
const tmp=()=>fs.mkdtempSync(path.join(os.tmpdir(),'paper-cont-'))
function terminal(file){const s=new PaperAutoExecutionLifecycleStore({filePath:file,idFactory:()=> 'old-life'});s.create({selectedSymbol:'BTG'});s.transition('ENTER_SUBMITTING',{enterClientOrderId:'e'});s.transition('ENTER_UNKNOWN',{enterBrokerOrderId:'eb'});s.transition('POSITION_CONFIRMED',{filledQuantity:1,averageFillPrice:4.12,brokerPositionIdentity:'BTG:1'});s.transition('MONITORING');s.transition('EXIT_TRIGGERED',{exitClientOrderId:'x'});s.transition('EXIT_SUBMITTING',{exitBrokerOrderId:'xb'});return s.transition('ROUND_TRIP_COMPLETED')}
test('terminal preserved and no candidate creates nothing',async()=>{const d=tmp(),old=path.join(d,'old.json'),before=terminal(old);let active=old;const r=createPaperAutoExecutionContinuityRuntime({env:{PAPER_AUTO_CONTINUITY_ENABLED:'1'},runsDir:d,getActiveLifecycleFile:()=>active,setActiveLifecycleFile:f=>{active=f},getScanSnapshot:async()=>({candidates:[]}),idFactory:()=> 'new-life'});const out=await r.runOnce();assert.equal(out.lastStatus,'NO_ELIGIBLE_CANDIDATE');assert.equal(active,old);assert.deepEqual(new PaperAutoExecutionLifecycleStore({filePath:old}).load(),before)})
test('eligible ENTER creates one fresh lifecycle and preserves terminal evidence',async()=>{const d=tmp(),old=path.join(d,'old.json'),before=terminal(old);let active=old;const r=createPaperAutoExecutionContinuityRuntime({env:{PAPER_AUTO_CONTINUITY_ENABLED:'1'},runsDir:d,getActiveLifecycleFile:()=>active,setActiveLifecycleFile:f=>{active=f},getScanSnapshot:async()=>({observedAt:'2026-08-13T01:00:00Z',candidates:[{symbol:'NEW',state:'ENTER',buyRecommendation:true,score:9}]}),idFactory:()=> 'new-life'});const out=await r.runOnce();assert.equal(out.lastStatus,'FRESH_CANDIDATE_LIFECYCLE_CREATED');assert.notEqual(active,old);assert.equal(out.lastLifecycle.state,'CANDIDATE_SELECTED');assert.equal(out.lastLifecycle.selectedSymbol,'NEW');assert.equal(out.lastLifecycle.enterIdentity.phase,'enter');assert.deepEqual(new PaperAutoExecutionLifecycleStore({filePath:old}).load(),before)})
test('concurrent cycles deduplicate and active nonterminal blocks replacement',async()=>{const d=tmp(),old=path.join(d,'old.json');terminal(old);let active=old,scans=0;const r=createPaperAutoExecutionContinuityRuntime({env:{PAPER_AUTO_CONTINUITY_ENABLED:'1'},runsDir:d,getActiveLifecycleFile:()=>active,setActiveLifecycleFile:f=>{active=f},getScanSnapshot:async()=>{scans++;await new Promise(x=>setTimeout(x,10));return{candidates:[{symbol:'ABC',state:'ENTER',buyRecommendation:true}]}},idFactory:()=> 'only-one'});const[a,b]=await Promise.all([r.runOnce(),r.runOnce()]);assert.equal(scans,1);assert.equal(a.lastLifecycleFile,b.lastLifecycleFile);const c=await r.runOnce();assert.equal(c.lastStatus,'ACTIVE_NONTERMINAL_LIFECYCLE_PRESENT')})
test('disabled by default and safety is nonmutating',async()=>{const r=createPaperAutoExecutionContinuityRuntime({env:{},getScanSnapshot:async()=>({candidates:[{symbol:'XYZ',state:'ENTER',buyRecommendation:true}]})});const out=await r.runOnce();assert.equal(out.lastStatus,'CONTINUITY_DISABLED_BY_ENV');assert.equal(out.safety.paperOnly,true);assert.equal(out.safety.brokerContactAllowed,false);assert.equal(out.safety.orderPlacementAllowed,false);assert.equal(out.safety.accountMutationAllowed,false);assert.equal(out.safety.liveTradingAllowed,false)})
