module.exports = {
  apps: [
    {
      name: "gemini-scanner",
      cwd: "/home/gemini/apps/gemini-scanner-backend",
      script: "./src/server.js",
      interpreter: "/usr/bin/node",
      exec_mode: "fork",
      env: {
        NODE_ENV: "production",
        PAPER_AUTO_EXIT_MONITOR_ENABLED: "1",
        PAPER_AUTO_EXIT_MONITOR_LIFECYCLE_PATH: "/home/gemini/apps/gemini-scanner-backend/runs/paper_auto_exit_controlled_adoption_btg_20260811.json",
      },
    },
    {
      name: "gemini-ops-ai-watchdog",
      cwd: "/home/gemini/apps/gemini-scanner-backend",
      script: "./scripts/run_ops_ai_scanner_watchdog.mjs",
      interpreter: "/usr/bin/node",
      exec_mode: "fork",
      autorestart: true,
      restart_delay: 5000,
      max_restarts: 20,
      env: {
        NODE_ENV: "production",
        GS_WATCHDOG_INTERVAL_MS: "60000",
        GS_WATCHDOG_EMAIL_SEND_AUTHORIZED: "true",
      },
    },
    {
      name: "gemini-infrastructure-watchdog",
      cwd: "/home/gemini/apps/gemini-scanner-backend",
      script: "./scripts/run_infrastructure_website_watchdog.mjs",
      interpreter: "/usr/bin/node",
      exec_mode: "fork",
      autorestart: true,
      restart_delay: 5000,
      max_restarts: 20,
      env: {
        NODE_ENV: "production",
        GS_INFRA_WATCHDOG_INTERVAL_MS: "60000",
        GS_INFRA_WATCHDOG_EMAIL_SEND_AUTHORIZED: "true",
      },
    },
    {
      name: "gemini-execution-readiness-watcher",
      cwd: "/home/gemini/apps/gemini-scanner-backend",
      script: "./scripts/run_execution_readiness_watcher.mjs",
      interpreter: "/usr/bin/node",
      exec_mode: "fork",
      autorestart: true,
      restart_delay: 5000,
      max_restarts: 20,
      env: { NODE_ENV: "production", GS_EXECUTION_READINESS_WATCH_INTERVAL_MS: "30000" },
    },
  ],
};
