module.exports = {
  apps: [
    {
      name: "gemini-scanner",
      cwd: "/home/gemini/apps/gemini-scanner-backend",
      script: "./src/server.js",
      interpreter: "/usr/bin/node",
      exec_mode: "fork",
      env: {
        NODE_ENV: "production",
        GS_ADMIN_PAPER_ALERT_EMAIL_SEND_AUTHORIZED: "true",
        GS_PAPER_EXECUTION_EMAIL_SEND_AUTHORIZED: "true",
        PAPER_AUTO_DEGRADED_BROKER_MODE_ENABLED: "1",
        PAPER_AUTO_EXIT_MONITOR_ENABLED: "1",
      PAPER_AUTO_CONTINUITY_ENABLED: "1",
      PAPER_AUTO_CONTINUITY_ENTER_ENABLED: "1",
      PAPER_AUTO_CONTINUITY_CANDIDATE_EXPIRATION_ENABLED: "1",
      PAPER_AUTO_MULTI_LIFECYCLE_ENABLED: "1",
      PAPER_AUTO_SCALE_RUNNER_ENABLED: "1",
      PAPER_AUTO_SCALE_IN_SUBMISSION_ENABLED: "1",
      PAPER_AUTO_SCALE_OUT_SUBMISSION_ENABLED: "1",
        PAPER_AUTO_EXIT_REPLACEMENT_RUNNER_ENABLED: "1",
        PAPER_AUTO_EXIT_REPLACEMENT_SUBMISSION_BOUNDARY_ENABLED: "1",
        PAPER_AUTO_EXIT_REPLACEMENT_SUBMISSION_ENABLED: "1",
        PAPER_AUTO_EXIT_MONITOR_LIFECYCLE_PATH: "/home/gemini/apps/gemini-scanner-backend/runs/paper_auto_exit_controlled_adoption_btg_20260811.json",
      },
    },
    {
      name: "gemini-ops-ai-watchdog",
      cwd: "/home/gemini/apps/gemini-scanner-backend",
      script: "./scripts/run_ops_ai_scanner_watchdog.mjs",
      interpreter: "/usr/bin/node",
      exec_mode: "fork",
      autorestart: true,
      restart_delay: 5000,
      max_restarts: 20,
      env: {
        NODE_ENV: "production",
        GS_WATCHDOG_INTERVAL_MS: "60000",
        GS_WATCHDOG_EMAIL_SEND_AUTHORIZED: "true",
      },
    },
    {
      name: "gemini-infrastructure-watchdog",
      cwd: "/home/gemini/apps/gemini-scanner-backend",
      script: "./scripts/run_infrastructure_website_watchdog.mjs",
      interpreter: "/usr/bin/node",
      exec_mode: "fork",
      autorestart: true,
      restart_delay: 5000,
      max_restarts: 20,
      env: {
        NODE_ENV: "production",
        GS_INFRA_WATCHDOG_INTERVAL_MS: "60000",
        GS_INFRA_WATCHDOG_EMAIL_SEND_AUTHORIZED: "true",
      },
    },
    {
      name: "gemini-execution-readiness-watcher",
      cwd: "/home/gemini/apps/gemini-scanner-backend",
      script: "./scripts/run_execution_readiness_watcher.mjs",
      interpreter: "/usr/bin/node",
      exec_mode: "fork",
      autorestart: true,
      restart_delay: 5000,
      max_restarts: 20,
      env: { NODE_ENV: "production", GS_EXECUTION_READINESS_WATCH_INTERVAL_MS: "30000" },
    },
    {
      name: "gemini-execution-assurance-watchdog",
      cwd: "/home/gemini/apps/gemini-scanner-backend",
      script: "./scripts/run_paper_auto_execution_execution_assurance_watchdog.mjs",
      interpreter: "/usr/bin/node",
      exec_mode: "fork",
      autorestart: true,
      restart_delay: 5000,
      max_restarts: 20,
      env: {
        NODE_ENV: "production",
        GS_EXECUTION_ASSURANCE_WATCH_INTERVAL_MS: "30000",
        GS_ADMIN_PAPER_ALERT_EMAIL_SEND_AUTHORIZED: "true",
        GS_EXECUTION_ASSURANCE_SAFE_REPAIR_AUTHORIZED: "true",
      },
    },
    {
      name: "gemini-under-five-cadence-verifier",
      cwd: "/home/gemini/apps/gemini-scanner-backend",
      script: "./scripts/run_alpaca_under_five_cadence_verifier.mjs",
      interpreter: "/usr/bin/node",
      exec_mode: "fork",
      autorestart: true,
      restart_delay: 5000,
      max_restarts: 20,
      env: {
        NODE_ENV: "production",
        GS_CADENCE_VERIFIER_INTERVAL_MS: "15000",
        GS_CADENCE_VERIFIER_EMAIL_SEND_AUTHORIZED: "true",
      },
    },
  ],
};
