import fs from "node:fs";
import path from "node:path";
import crypto from "node:crypto";
export const VERSION="ops_ai_scanner_watchdog_v1";
export const DEFAULT_INCIDENT_LEDGER_PATH=path.resolve("runs/ops_ai_scanner_watchdog_incidents.jsonl");
const LOCKS=["orderPlacementAllowed","brokerContactAllowed","accountMutationAllowed","scannerLogicMutationAllowed","thresholdMutationAllowed","automaticLearningAllowed","liveTradingAllowed","enterEnabled"];
const age=(now,v)=>{const t=Date.parse(v??"");return Number.isFinite(t)?Math.max(0,now.getTime()-t):null};
const c=(id,ok,code,detail={},applicable=true)=>Object.freeze({id,applicable,ok:applicable?ok===true:true,status:!applicable?"not_applicable":ok?"pass":"fail",code:!applicable||ok?null:code,detail:Object.freeze({...detail})});
const key=r=>crypto.createHash("sha256").update(JSON.stringify([...(r?.failureCodes??[])].sort())).digest("hex").slice(0,24);
export function evaluateOpsAiScannerWatchdog(input={},options={}){
 const now=options.now instanceof Date?options.now:new Date(options.now??Date.now()); if(!Number.isFinite(now.getTime()))throw new TypeError("invalid_now");
 const h=input.health??{},r=input.readiness??{},pm=Array.isArray(input.pm2)?input.pm2:[],pre=input.premarket??{},post=input.postMarket??{},ai=input.backgroundAi??{},records=Array.isArray(input.aiReviewRecords)?input.aiReviewRecords:[],latest=records[0]??null,s=input.session??{};
 const proc=new Map(pm.map(x=>[String(x?.name??""),String(x?.status??"")])); const expected={"gemini-scanner":"online","gemini-dry-scanner":"stopped"}; const mismatches=Object.entries(expected).filter(([n,v])=>proc.get(n)!==v).map(([name,expected])=>({name,expected,actual:proc.get(name)??"missing"}));
 const violations=[]; for(const src of [h,r,pre,post,ai,latest].filter(Boolean))for(const f of LOCKS)if(src?.[f]===true)violations.push(f);
 const preApp=s.premarketApplicable===true||pre?.session?.active===true, postApp=s.postMarketEvidenceExpected===true, aiApp=s.backgroundAiExpected!==false;
 const preMax=Number(options.maxPremarketAgeMs??600000),postMax=Number(options.maxPostMarketAgeMs??1800000),aiMax=Number(options.maxAiAgeMs??Math.max(Number(ai.intervalMs??900000)*2,1800000));
 const preAge=age(now,pre.lastAutomaticScanAt),postAge=age(now,post?.lastResult?.generatedAt??post.lastCompletedAt),aiAge=age(now,latest?.generatedAt);
 const checks=[
 c("health",h.status==="ok"&&h.degraded!==true,"HEALTH_DEGRADED",{status:h.status??null,degraded:h.degraded===true,issues:Array.isArray(h.issues)?h.issues:[]}),
 c("readiness",r.ready===true&&r.degraded!==true,"READINESS_FAILED",{ready:r.ready===true,degraded:r.degraded===true,issues:Array.isArray(r.issues)?r.issues:[]}),
 c("pm2_process_invariants",mismatches.length===0,"PM2_PROCESS_INVARIANT_FAILED",{mismatches}),
 c("premarket_scheduler",pre.running===true&&pre.schedulerState!=="error","PREMARKET_SCHEDULER_UNHEALTHY",{running:pre.running===true,schedulerState:pre.schedulerState??null,lastError:pre.lastError??null,nextWakeAt:pre.nextWakeAt??null}),
 c("premarket_evidence_freshness",preAge!==null&&preAge<=preMax&&pre.lastAutomaticScanSkipped!==true,"PREMARKET_EVIDENCE_STALE",{lastAutomaticScanAt:pre.lastAutomaticScanAt??null,ageMs:preAge,maxAgeMs:preMax,skipped:pre.lastAutomaticScanSkipped===true},preApp),
 c("postmarket_scheduler",post.enabled===true&&post.running===true&&post.lastStatus!=="worker_error","POSTMARKET_SCHEDULER_UNHEALTHY",{enabled:post.enabled===true,running:post.running===true,timerScheduled:post.timerScheduled===true,lastStatus:post.lastStatus??null,nextWakeAt:post.nextWakeAt??null}),
 c("postmarket_evidence_freshness",postAge!==null&&postAge<=postMax&&["completed_readonly","duplicate_snapshot_suppressed"].includes(String(post?.lastResult?.status??post.lastStatus??"")),"POSTMARKET_EVIDENCE_STALE",{lastCompletedAt:post.lastCompletedAt??null,resultGeneratedAt:post?.lastResult?.generatedAt??null,resultStatus:post?.lastResult?.status??null,ageMs:postAge,maxAgeMs:postMax},postApp),
 c("background_ai_worker",ai.enabled===true&&ai.running===true&&!["worker_error","runner_unavailable","stopped","disabled"].includes(String(ai.lastStatus??"")),"BACKGROUND_AI_WORKER_UNHEALTHY",{enabled:ai.enabled===true,running:ai.running===true,intervalMs:ai.intervalMs??null,lastStatus:ai.lastStatus??null,lastErrorCode:ai.lastErrorCode??null},aiApp),
 c("recent_openai_response",latest?.provider==="openai"&&latest?.providerStatus==="completed_readonly"&&typeof latest?.responseId==="string"&&latest.responseId.trim()&&aiAge!==null&&aiAge<=aiMax,"OPENAI_RESPONSE_MISSING_OR_STALE",{provider:latest?.provider??null,providerStatus:latest?.providerStatus??null,responseIdPresent:Boolean(latest?.responseId),generatedAt:latest?.generatedAt??null,ageMs:aiAge,maxAgeMs:aiMax},aiApp),
 c("ai_review_ledger_persistence",input.aiLedger?.available===true&&input.aiLedger?.writable===true,"AI_LEDGER_PERSISTENCE_FAILED",{available:input.aiLedger?.available===true,writable:input.aiLedger?.writable===true,path:input.aiLedger?.path??null}),
 c("incident_ledger_persistence",input.incidentLedger?.available===true&&input.incidentLedger?.writable===true,"INCIDENT_LEDGER_PERSISTENCE_FAILED",{available:input.incidentLedger?.available===true,writable:input.incidentLedger?.writable===true,path:input.incidentLedger?.path??null}),
 c("mutation_locks_closed",violations.length===0,"MUTATION_LOCK_OPEN",{violations:[...new Set(violations)].sort()})];
 const failures=checks.filter(x=>x.applicable&&!x.ok); return Object.freeze({version:VERSION,generatedAt:now.toISOString(),status:failures.length?"unhealthy":"healthy",healthy:failures.length===0,failureCount:failures.length,failureCodes:Object.freeze(failures.map(x=>x.code)),checks:Object.freeze(checks),readOnly:true,paperOnly:true,decisionAssistOnly:true,remediationAllowed:false,automaticLearningAllowed:false,scannerLogicMutationAllowed:false,thresholdMutationAllowed:false,orderPlacementAllowed:false,brokerContactAllowed:false,accountMutationAllowed:false,liveTradingAllowed:false,enterEnabled:false});
}
export function buildWatchdogIncidentTransition(report,previous=null,options={}){const now=new Date(options.now??report?.generatedAt??Date.now()),cool=Math.max(0,Number(options.cooldownMs??3600000)),esc=Math.max(cool,Number(options.escalationAfterMs??14400000)),bad=report?.healthy!==true,was=previous?.open===true,opened=was?previous.openedAt:bad?now.toISOString():null,dur=opened?Math.max(0,now-Date.parse(opened)):0,same=was&&previous.incidentKey===key(report),la=Date.parse(previous?.lastAlertAt??""),elapsed=!Number.isFinite(la)||now-la>=cool;let transition="none",shouldAlert=false;if(bad&&!was){transition="failure_opened";shouldAlert=true}else if(!bad&&was){transition="recovered";shouldAlert=true}else if(bad&&was&&(!same||(dur>=esc&&elapsed))){transition=same?"failure_escalated":"failure_changed";shouldAlert=true}return Object.freeze({version:VERSION,transition,shouldAlert,open:bad,incidentKey:bad?key(report):null,openedAt:opened,lastObservedAt:now.toISOString(),lastAlertAt:shouldAlert?now.toISOString():previous?.lastAlertAt??null,durationMs:dur,failureCodes:Object.freeze([...(report?.failureCodes??[])]),alertKind:transition==="recovered"?"recovery":shouldAlert?"failure":null,deduplicated:bad&&was&&same&&!shouldAlert,cooldownMs:cool,escalationAfterMs:esc,readOnly:true,remediationAllowed:false})}
const json=l=>{try{return JSON.parse(l)}catch{return null}};
export function readLatestWatchdogIncident(options={}){const p=path.resolve(options.ledgerPath??DEFAULT_INCIDENT_LEDGER_PATH);if(!fs.existsSync(p))return null;return fs.readFileSync(p,"utf8").split(/\r?\n/).filter(Boolean).map(json).filter(Boolean).at(-1)??null}
export function appendWatchdogIncidentRecord(record,options={}){const p=path.resolve(options.ledgerPath??DEFAULT_INCIDENT_LEDGER_PATH);fs.mkdirSync(path.dirname(p),{recursive:true,mode:0o700});fs.appendFileSync(p,`${JSON.stringify(record)}\n`,{encoding:"utf8",mode:0o600});try{fs.chmodSync(p,0o600)}catch{}return Object.freeze({appended:true,ledgerPath:p,localJsonlOnly:true,containsSecrets:false})}
export default Object.freeze({VERSION,DEFAULT_INCIDENT_LEDGER_PATH,evaluateOpsAiScannerWatchdog,buildWatchdogIncidentTransition,readLatestWatchdogIncident,appendWatchdogIncidentRecord});
