import fs from "node:fs";
import path from "node:path";
import { execFile } from "node:child_process";
import { promisify } from "node:util";
import { DEFAULT_BACKGROUND_AI_REVIEW_PATH, listCustomerReportBackgroundAiReviewRecords } from "./customer_report_background_ai_review_store.mjs";
import { DEFAULT_INCIDENT_LEDGER_PATH, evaluateOpsAiScannerWatchdog, buildWatchdogIncidentTransition, readLatestWatchdogIncident, appendWatchdogIncidentRecord } from "./ops_ai_scanner_watchdog.mjs";
export const VERSION = "ops_ai_scanner_watchdog_runtime_v1";
const execFileAsync = promisify(execFile);
const clean = (value, max = 500) => { const text = String(value ?? "").trim(); return text.length > max ? text.slice(0, max) : text; };
const safeJson = (text) => { try { return JSON.parse(text); } catch { return null; } };
export function createWatchdogHttpAdapter({ fetchImpl = globalThis.fetch, baseUrl = "http://127.0.0.1:3000", timeoutMs = 10000 } = {}) {
  async function getJson(route) { if (typeof fetchImpl !== "function") throw new Error("WATCHDOG_FETCH_UNAVAILABLE"); const controller = new AbortController(); const timer = setTimeout(() => controller.abort(), timeoutMs); timer?.unref?.(); try { const response = await fetchImpl(`${baseUrl}${route}`, { method: "GET", headers: { Accept: "application/json" }, signal: controller.signal }); const body = await response.json().catch(() => ({})); return Object.freeze({ statusCode: response.status, ok: response.ok, body }); } finally { clearTimeout(timer); } }
  return Object.freeze({ getJson });
}
export function createWatchdogPm2Adapter({ execFileImpl = execFileAsync } = {}) { return Object.freeze({ async list() { const { stdout } = await execFileImpl("pm2", ["jlist"], { maxBuffer: 2 * 1024 * 1024, timeout: 10000 }); const rows = safeJson(stdout); if (!Array.isArray(rows)) throw new Error("PM2_JLIST_INVALID"); return Object.freeze(rows.map((row) => Object.freeze({ name: clean(row?.name, 120), status: clean(row?.pm2_env?.status, 64) || "unknown" }))); } }); }
export function createWatchdogFilesystemAdapter({ fsImpl = fs } = {}) { return Object.freeze({ inspectFile(filePath) { const resolved = path.resolve(filePath); try { fsImpl.mkdirSync(path.dirname(resolved), { recursive: true, mode: 0o700 }); if (!fsImpl.existsSync(resolved)) fsImpl.closeSync(fsImpl.openSync(resolved, "a", 0o600)); try { fsImpl.chmodSync(resolved, 0o600); } catch {} const stat = fsImpl.statSync(resolved); return Object.freeze({ path: resolved, available: stat.isFile(), writable: (stat.mode & 0o200) !== 0, mode: stat.mode & 0o777 }); } catch (error) { return Object.freeze({ path: resolved, available: false, writable: false, mode: null, errorCode: clean(error?.code ?? error?.name ?? "FILE_INSPECTION_FAILED", 120) }); } } }); }
export function buildOpsAiScannerWatchdogAlert({ report = {}, transition = {}, recipient, sender } = {}) { const kind = transition?.alertKind === "recovery" ? "RECOVERY" : "FAILURE"; const codes = Array.isArray(report?.failureCodes) ? report.failureCodes : []; return Object.freeze({ to: clean(recipient, 320), from: clean(sender, 320), subject: `[GeminiScanner Watchdog] ${kind}: ${report.status ?? "unknown"}`, text: [`GeminiScanner Ops AI Scanner Watchdog ${kind}`, "", `Generated: ${report.generatedAt ?? "unknown"}`, `Status: ${report.status ?? "unknown"}`, `Transition: ${transition?.transition ?? "unknown"}`, `Failure count: ${Number(report?.failureCount ?? 0)}`, `Failure codes: ${codes.length ? codes.join(", ") : "none"}`, "", "Read-only diagnostics only. No remediation, broker contact, order placement, account mutation, threshold mutation, ENTER enablement, or live-trading action was performed."].join("\n"), containsSecrets: false, readOnly: true }); }
export function createWatchdogEmailAdapter({ fetchImpl = globalThis.fetch, apiKey = process.env.RESEND_API_KEY, provider = process.env.CUSTOMER_EMAIL_PROVIDER, sender = process.env.CUSTOMER_EMAIL_FROM, recipient = process.env.GS_WATCHDOG_ALERT_RECIPIENT } = {}) { return Object.freeze({ configured: clean(provider).toLowerCase() === "resend" && Boolean(clean(apiKey)) && Boolean(clean(sender)) && Boolean(clean(recipient)), async send(message) { if (clean(provider).toLowerCase() !== "resend") return Object.freeze({ delivered: false, reason: "email_provider_not_configured" }); if (!clean(apiKey) || !clean(sender) || !clean(recipient) || typeof fetchImpl !== "function") return Object.freeze({ delivered: false, reason: "resend_not_configured" }); const response = await fetchImpl("https://api.resend.com/emails", { method: "POST", headers: { Authorization: `Bearer ${apiKey}`, "Content-Type": "application/json" }, body: JSON.stringify({ from: clean(sender), to: [clean(recipient)], subject: message.subject, text: message.text }) }); const body = await response.json().catch(() => ({})); return Object.freeze({ delivered: response.ok && Boolean(clean(body?.id)), provider: "resend", deliveryId: clean(body?.id) || null, statusCode: response.status }); } }); }
export async function collectOpsAiScannerWatchdogInput({ http, pm2, filesystem, aiLedgerPath = DEFAULT_BACKGROUND_AI_REVIEW_PATH, incidentLedgerPath = DEFAULT_INCIDENT_LEDGER_PATH, statusRoute = "/customer/scanner" } = {}) { const [healthResult, readinessResult, pm2Rows, scannerResult] = await Promise.all([http.getJson("/health"), http.getJson("/readiness"), pm2.list(), http.getJson(statusRoute)]); const scanner = scannerResult?.body ?? {}; const aiRecords = listCustomerReportBackgroundAiReviewRecords({ ledgerPath: aiLedgerPath, maxRecords: 20 }); return Object.freeze({ health: healthResult?.body ?? {}, readiness: readinessResult?.body ?? {}, pm2: pm2Rows, premarket: scanner?.premarketAutoStatus ?? scanner?.scanner?.premarketAutoStatus ?? {}, postMarket: scanner?.postMarketAutoStatus ?? scanner?.scanner?.postMarketAutoStatus ?? {}, backgroundAi: scanner?.backgroundAiReviewStatus ?? scanner?.scanner?.backgroundAiReviewStatus ?? {}, aiReviewRecords: aiRecords.records, aiLedger: filesystem.inspectFile(aiLedgerPath), incidentLedger: filesystem.inspectFile(incidentLedgerPath), session: scanner?.watchdogSession ?? {} }); }
export async function runOpsAiScannerWatchdogOnce(options = {}) { const now = options.now instanceof Date ? options.now : new Date(options.now ?? Date.now()); const http = options.http ?? createWatchdogHttpAdapter(options.httpOptions); const pm2 = options.pm2 ?? createWatchdogPm2Adapter(options.pm2Options); const filesystem = options.filesystem ?? createWatchdogFilesystemAdapter(options.filesystemOptions); const email = options.email ?? createWatchdogEmailAdapter(options.emailOptions); const incidentLedgerPath = options.incidentLedgerPath ?? DEFAULT_INCIDENT_LEDGER_PATH; const input = options.input ?? await collectOpsAiScannerWatchdogInput({ http, pm2, filesystem, aiLedgerPath: options.aiLedgerPath, incidentLedgerPath, statusRoute: options.statusRoute }); const report = evaluateOpsAiScannerWatchdog(input, { now, maxPremarketAgeMs: options.maxPremarketAgeMs, maxPostMarketAgeMs: options.maxPostMarketAgeMs, maxAiAgeMs: options.maxAiAgeMs }); const previous = options.previousIncident ?? readLatestWatchdogIncident({ ledgerPath: incidentLedgerPath }); const transition = buildWatchdogIncidentTransition(report, previous, { now, cooldownMs: options.cooldownMs, escalationAfterMs: options.escalationAfterMs }); const persistence = appendWatchdogIncidentRecord(Object.freeze({ ...transition, reportStatus: report.status, failureCount: report.failureCount, failureCodes: report.failureCodes }), { ledgerPath: incidentLedgerPath }); let alert = Object.freeze({ attempted: false, delivered: false, reason: "transition_not_alertable" }); if (transition.shouldAlert && options.allowEmailSend === true) { const message = buildOpsAiScannerWatchdogAlert({ report, transition, recipient: options.recipient ?? process.env.GS_WATCHDOG_ALERT_RECIPIENT, sender: options.sender ?? process.env.CUSTOMER_EMAIL_FROM }); alert = Object.freeze({ attempted: true, ...(await email.send(message)) }); } else if (transition.shouldAlert) alert = Object.freeze({ attempted: false, delivered: false, reason: "email_send_not_authorized" }); return Object.freeze({ version: VERSION, report, transition, persistence, alert, readOnly: true, remediationAllowed: false, emailSendAuthorized: options.allowEmailSend === true }); }
export default Object.freeze({ VERSION, createWatchdogHttpAdapter, createWatchdogPm2Adapter, createWatchdogFilesystemAdapter, createWatchdogEmailAdapter, buildOpsAiScannerWatchdogAlert, collectOpsAiScannerWatchdogInput, runOpsAiScannerWatchdogOnce });
