import fs from "node:fs";
import path from "node:path";
export const VERSION="paper_attempt_operator_review_packet_v1";
export const LOCKS=Object.freeze({decisionAssistOnly:true,monitorOnly:true,diagnosticsOnly:true,reviewOnly:true,liveTradingAllowed:false,autoTradingAllowed:false,accountMutationAllowed:false,brokerOrderPlacementAllowed:false,brokerContactAllowed:false,operatorCanPlaceOrderFromPacket:false});
const P={safetyFinalization:/^paper_attempt_safety_finalization_.*\.json$/,safetyFinalizationHandoff:/^compact_handoff_paper_attempt_safety_finalization_.*\.txt$/,controlCenter:/^paper_attempt_control_center.*\.json$/,manualPaperTradingReadinessAudit:/^manual_paper_trading_readiness_audit_.*\.json$/,firstTinyPaperOrderControlPath:/^first_tiny_paper_order_control_path_.*\.json$/,paperBrokerApproval:/^paper_broker.*approval.*\.json$/};
function rd(d){try{return fs.readdirSync(d,{withFileTypes:true})}catch{return[]}}
function js(f){try{return JSON.parse(fs.readFileSync(f,"utf8"))}catch{return null}}
function latest(root,re){const dir=path.join(root,"runs");return rd(dir).filter(e=>e.isFile()&&re.test(e.name)).map(e=>{const f=path.join(dir,e.name);let m=0;try{m=fs.statSync(f).mtimeMs}catch{}return{file:e.name,path:path.relative(root,f),mtimeMs:m}}).sort((a,b)=>b.mtimeMs-a.mtimeMs)[0]??null}
export function buildPacket(o={}){const root=o.projectRoot??process.cwd();const artifacts={};for(const[k,re]of Object.entries(P)){const x=latest(root,re);artifacts[k]={present:!!x,latestPath:x?.path??null,latestFile:x?.file??null}}const sj=artifacts.safetyFinalization.latestPath?js(path.join(root,artifacts.safetyFinalization.latestPath)):null;const safetyOk=sj?.ok===true&&sj?.safety?.safetyLocksOk===true;const req=["safetyFinalization","safetyFinalizationHandoff","controlCenter","manualPaperTradingReadinessAudit","firstTinyPaperOrderControlPath"];const miss=req.filter(k=>!artifacts[k].present);const warnings=[...miss.map(k=>`required_artifact_missing:${k}`),...(!artifacts.paperBrokerApproval.present?["optional_artifact_missing:paperBrokerApproval"]:[])];const blockers=[...(!safetyOk?["safety_finalization_not_clean"]:[]),...miss.map(k=>`missing_required_review_artifact:${k}`),"operator_review_packet_is_not_an_order_approval","broker_contact_still_blocked","order_placement_still_blocked"];return{ok:safetyOk&&miss.length===0,version:VERSION,generatedAt:new Date(o.now??Date.now()).toISOString(),status:safetyOk&&miss.length===0?"ready_for_human_review":"blocked",packetType:"operator_review_packet",safety:{...LOCKS,safetyFinalizationOk:safetyOk,safetyLocksOk:safetyOk},reviewDecision:{canApproveOrderPlacement:false,canContactBroker:false,canMutateAccount:false,finalDecision:"NO_GO_FOR_ORDER_PLACEMENT",reviewOnlyNextStep:"human_review_of_artifacts_only"},artifacts,warnings,blockers,checklist:[{id:"review_safety_finalization",passed:safetyOk},{id:"review_control_center",passed:artifacts.controlCenter.present},{id:"confirm_no_broker_contact",passed:LOCKS.brokerContactAllowed===false},{id:"confirm_no_order_placement",passed:LOCKS.brokerOrderPlacementAllowed===false}],nextActions:["review_packet_only","keep_decision_assist_only","do_not_place_orders_without_separate_future_approval"]}}
export function handoff(p,branch="feature/p3-quality-confidence-v1"){const a=Object.entries(p.artifacts).map(([k,v])=>`- ${k}: ${v.present?v.latestPath:"missing"}`).join("\n");return[`BEGIN GEMINISCANNER COMPACT HANDOFF`,``,`Project: GeminiScanner backend`,`Server: gemini-vps`,`Remote project path: ~/apps/gemini-scanner-backend`,`Branch: ${branch}`,``,`Automation rule:`,`- Stay at local Termux prompt: ~ $`,`- Commands must use: : GS_RUN_B64_V1; ~/bin/gsremote '<base64-payload>'`,`- Do not use raw ssh/cd workflow unless explicitly requested.`,``,`Current key point:`,`- Paper Attempt Operator Review Packet v1 complete.`,`- Packet is review-only and cannot approve broker contact or order placement.`,`- Safety posture remains decision-assist, monitor-only, diagnostics-only.`,``,`Latest artifacts:`,a,``,`Next suggested stage:`,`- Build Paper Attempt Operator Review Packet Panel v1 or continue the next paper-attempt control layer.`,``,`END GEMINISCANNER COMPACT HANDOFF`].join("\n")}
export function writeReport(o={}){const root=o.projectRoot??process.cwd();const p=buildPacket(o);const h=handoff(p,o.branch);const s=new Date(o.now??Date.now()).toISOString().replace(/[:.]/g,"-");const jp=path.join(root,"runs",`paper_attempt_operator_review_packet_${s}.json`);const hp=path.join(root,"runs",`compact_handoff_paper_attempt_operator_review_packet_${s}.txt`);fs.mkdirSync(path.dirname(jp),{recursive:true});fs.writeFileSync(jp,JSON.stringify({...p,compactHandoff:h},null,2)+"\n");fs.writeFileSync(hp,h+"\n");return{...p,output:{jsonPath:path.relative(root,jp),handoffPath:path.relative(root,hp)},compactHandoff:h}}
export default buildPacket;
