import { buildPaperUserApprovedDisabledOperatorPreview } from "../../scripts/preview_paper_user_approved_disabled_chain.mjs";
export const VERSION = "paper_user_approved_disabled_app_screen_v1";
export const ROUTE = "/app/paper-user-approved-disabled-preview";
const A=v=>Array.isArray(v)?v:[];
const E=v=>String(v??"").replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;").replaceAll("'","&#39;");
const F=v=>String(v??"").replaceAll(":"," — ").replaceAll("_"," ");
export async function buildPaperUserApprovedDisabledAppScreen(input={},nowMs=Date.now()){
 const preview=await buildPaperUserApprovedDisabledOperatorPreview(input,nowMs);
 return Object.freeze({version:VERSION,route:ROUTE,appScreen:true,title:"User-Approved Paper Trade Preview",subtitle:"Stage 2 mechanical preview with execution disabled by design.",displayState:preview.status,lastUpdatedAt:new Date(nowMs).toISOString(),preview,blockers:preview.blockers,readOnly:true,previewOnly:true,approvalControlsPresent:false,executionControlsPresent:false,executionEnabled:false,orderPlacementAllowed:false,brokerContactAllowed:false,accountMutationAllowed:false,stage3Locked:true});
}
export function renderPaperUserApprovedDisabledAppScreenHtml(screen={}){
 const p=screen.preview&&typeof screen.preview==="object"?screen.preview:{};
 const blockers=A(screen.blockers).length?A(screen.blockers).map(x=>`<li>${E(F(x))}</li>`).join(""):"<li>none</li>";
 return `<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${E(screen.title)}</title><style>body{font-family:system-ui;margin:0;background:#f4fbf6;color:#0b1220;padding:14px}.wrap{max-width:860px;margin:auto}.hero,.card,.safety{background:white;border:1px solid #d8eee1;border-radius:22px;padding:16px;margin:12px 0}.hero{background:linear-gradient(135deg,#07140f,#0b3322);color:white}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(220px,1fr));gap:10px}.metric{background:#f8fffb;border:1px solid #d8eee1;border-radius:16px;padding:12px}.pill{display:inline-block;border-radius:999px;padding:7px 10px;background:#eafff1;margin:0 6px 6px 0}.locked{background:#fff3f3;border-color:#ffd1d1}</style></head><body><main class="wrap"><section class="hero"><h1>${E(screen.title)}</h1><p>${E(screen.subtitle)}</p><p><b>${E(screen.displayState)}</b></p><p>Last updated: ${E(screen.lastUpdatedAt)}</p></section><section class="card"><h2>Disabled mechanical chain</h2><div class="grid"><div class="metric"><b>Proposal</b><p>${E(p.proposalStatus)}</p><small>${E(p.proposalId??"none")}</small></div><div class="metric"><b>User approval</b><p>${E(p.approvalDecision)}</p></div><div class="metric"><b>Submission gate</b><p>${E(p.submissionDecision)}</p></div><div class="metric"><b>Adapter envelope</b><p>${E(p.adapterEnvelopeStatus)}</p></div><div class="metric"><b>Adapter result</b><p>${E(p.adapterResultStatus)}</p></div></div></section><section class="card locked"><h2>Current blockers</h2><ul>${blockers}</ul></section><section class="safety"><h2>Safety locks</h2><span class="pill">Paper only</span><span class="pill">Preview only</span><span class="pill">No approval button</span><span class="pill">No execution controls</span><p>executionEnabled=${E(screen.executionEnabled)} orderPlacementAllowed=${E(screen.orderPlacementAllowed)} brokerContactAllowed=${E(screen.brokerContactAllowed)} accountMutationAllowed=${E(screen.accountMutationAllowed)} stage3Locked=${E(screen.stage3Locked)}</p><p>This screen cannot approve, submit, place, cancel, or modify an order. It does not contact a broker and does not write evidence.</p></section><p><a href="/app">Back to GeminiScanner App</a></p></main></body></html>`;
}
export default buildPaperUserApprovedDisabledAppScreen;
