export const STATES = Object.freeze({
  IDLE:'IDLE', CANDIDATE_SELECTED:'CANDIDATE_SELECTED', ENTER_SUBMITTING:'ENTER_SUBMITTING',
  ENTER_UNKNOWN:'ENTER_UNKNOWN', ENTER_OPEN:'ENTER_OPEN', ENTER_PARTIALLY_FILLED:'ENTER_PARTIALLY_FILLED',
  POSITION_CONFIRMED:'POSITION_CONFIRMED', MONITORING:'MONITORING', EXIT_TRIGGERED:'EXIT_TRIGGERED',
  EXIT_SUBMITTING:'EXIT_SUBMITTING', EXIT_UNKNOWN:'EXIT_UNKNOWN', EXIT_PARTIALLY_FILLED:'EXIT_PARTIALLY_FILLED',
  ROUND_TRIP_COMPLETED:'ROUND_TRIP_COMPLETED', FAILED_NEEDS_REVIEW:'FAILED_NEEDS_REVIEW', CANDIDATE_EXPIRED:'CANDIDATE_EXPIRED',
  UNRESOLVED_NEEDS_RECONCILIATION:'UNRESOLVED_NEEDS_RECONCILIATION'
})
const S=STATES
const allowed=new Map([
 [S.IDLE,[S.CANDIDATE_SELECTED]],
 [S.CANDIDATE_SELECTED,[S.ENTER_SUBMITTING,S.FAILED_NEEDS_REVIEW,S.CANDIDATE_EXPIRED]],
 [S.ENTER_SUBMITTING,[S.ENTER_UNKNOWN,S.ENTER_OPEN,S.ENTER_PARTIALLY_FILLED,S.POSITION_CONFIRMED,S.UNRESOLVED_NEEDS_RECONCILIATION,S.FAILED_NEEDS_REVIEW]],
 [S.ENTER_UNKNOWN,[S.ENTER_OPEN,S.ENTER_PARTIALLY_FILLED,S.POSITION_CONFIRMED,S.UNRESOLVED_NEEDS_RECONCILIATION,S.FAILED_NEEDS_REVIEW]],
 [S.ENTER_OPEN,[S.ENTER_PARTIALLY_FILLED,S.POSITION_CONFIRMED,S.UNRESOLVED_NEEDS_RECONCILIATION,S.FAILED_NEEDS_REVIEW]],
 [S.ENTER_PARTIALLY_FILLED,[S.POSITION_CONFIRMED,S.UNRESOLVED_NEEDS_RECONCILIATION,S.FAILED_NEEDS_REVIEW]],
 [S.POSITION_CONFIRMED,[S.MONITORING,S.EXIT_TRIGGERED,S.FAILED_NEEDS_REVIEW]],
 [S.MONITORING,[S.EXIT_TRIGGERED,S.FAILED_NEEDS_REVIEW]],
 [S.EXIT_TRIGGERED,[S.EXIT_SUBMITTING,S.FAILED_NEEDS_REVIEW]],
 [S.EXIT_SUBMITTING,[S.EXIT_UNKNOWN,S.EXIT_PARTIALLY_FILLED,S.ROUND_TRIP_COMPLETED,S.FAILED_NEEDS_REVIEW]],
 [S.EXIT_UNKNOWN,[S.EXIT_PARTIALLY_FILLED,S.ROUND_TRIP_COMPLETED,S.UNRESOLVED_NEEDS_RECONCILIATION,S.FAILED_NEEDS_REVIEW]],
 [S.EXIT_PARTIALLY_FILLED,[S.ROUND_TRIP_COMPLETED,S.UNRESOLVED_NEEDS_RECONCILIATION,S.FAILED_NEEDS_REVIEW]],
 [S.UNRESOLVED_NEEDS_RECONCILIATION,[S.ENTER_OPEN,S.ENTER_PARTIALLY_FILLED,S.POSITION_CONFIRMED,S.EXIT_PARTIALLY_FILLED,S.ROUND_TRIP_COMPLETED,S.FAILED_NEEDS_REVIEW]],
 [S.ROUND_TRIP_COMPLETED,[S.IDLE]], [S.FAILED_NEEDS_REVIEW,[S.IDLE]], [S.CANDIDATE_EXPIRED,[S.IDLE]]
])
export function canTransition(from,to){return Boolean(allowed.get(from)?.includes(to))}
export function assertTransition(from,to){if(!Object.values(S).includes(from)||!Object.values(S).includes(to))throw new Error(`paper_auto_unknown_state:${from}->${to}`);if(!canTransition(from,to))throw new Error(`paper_auto_invalid_transition:${from}->${to}`);return true}
export const terminalStates=new Set([S.ROUND_TRIP_COMPLETED,S.FAILED_NEEDS_REVIEW,S.CANDIDATE_EXPIRED])
