import{buildAppNavigationReadonly as nav}from"./app_navigation_readonly.mjs";
export const VERSION="paper_app_broker_readiness_index_app_screen_v1";
export const ROUTE="/app/paper-app-broker-readiness-index";
const PAPER_BROKER_ADAPTER_APPROVAL_LOCK_TITLE="Paper Broker Adapter Approval Lock";
export const REQUIRED_ROUTES=Object.freeze(["/app/paper-app-safety-lock-status","/app/paper-broker-adapter-approval-lock","/app/paper-broker-adapter-approval-record-tool","/app/paper-broker-runtime-environment-preflight","/app/paper-broker-network-attempt-status","/app/paper-trade-broker-integration-preflight-stack","/app/paper-trade-broker-adapter-guard","/app/paper-trade-execution-control-stack","/app/paper-trade-operator-go-no-go","/app/paper-trade-readiness-report"]);
const S=Object.freeze({liveTradingAllowed:false,autoTradingAllowed:false,brokerExecutionAllowed:false,brokerContactAllowed:false,orderPlacementAllowed:false,orderSubmitAllowed:false,retryAllowed:false,resetAllowed:false,accountMutationAllowed:false,routeExecutionAllowed:false});
const A=v=>Array.isArray(v)?v:[],R=e=>String(e?.routeHref||e?.href||""),E=v=>String(v??"").replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;");
export function buildPaperAppBrokerReadinessIndexAppScreen({entries=null,now=new Date()}={}){
 const n=A(entries??nav({}).entries),set=new Set(n.map(R).filter(Boolean)),missingRequiredRoutes=REQUIRED_ROUTES.filter(x=>!set.has(x));
 const routes=n.filter(x=>R(x).startsWith("/app/")&&/paper|broker|preflight|adapter|execution|readiness|operator|safety|lock/i.test([x.id,x.title,x.category,R(x),x.displayState].join(" "))).map(x=>({id:String(x.id??""),title:String(x.title??x.id??""),routeHref:R(x),displayState:String(x.displayState??"")}));
 const checks={requiredRoutesLinked:missingRequiredRoutes.length===0,brokerReadinessRoutesPresent:routes.length>=REQUIRED_ROUTES.length,readOnly:true,monitorOnly:true,diagnosticsOnly:true,noExecutionControls:true,noBrokerContact:true,noOrderSubmit:true,noRetry:true,noReset:true,noAccountMutation:true,allSafetyLocksClosed:Object.values(S).every(v=>v===false)};
 const ready=Object.values(checks).every(Boolean);
 return{ok:true,version:VERSION,appScreen:true,route:ROUTE,title:"Paper App Broker Readiness Index",status:ready?"paper_app_broker_readiness_index_ready_readonly":"paper_app_broker_readiness_index_incomplete_readonly",displayState:ready?"PAPER_APP_BROKER_READINESS_INDEX_READY_READONLY":"PAPER_APP_BROKER_READINESS_INDEX_INCOMPLETE_READONLY",ts:now.toISOString(),readOnly:true,monitorOnly:true,diagnosticsOnly:true,noExecutionControls:true,noResetControls:true,safety:{...S},checks,summary:{totalNavigationEntries:n.length,brokerReadinessRouteCount:routes.length,requiredRouteCount:REQUIRED_ROUTES.length,missingRequiredRouteCount:missingRequiredRoutes.length},missingRequiredRoutes,routes};
}
export function renderPaperAppBrokerReadinessIndexAppScreenHtml(input={}){
 const x=input?.version===VERSION?input:buildPaperAppBrokerReadinessIndexAppScreen(input);
 const missing=new Set(A(x.missingRequiredRoutes));
 const required=A(REQUIRED_ROUTES).map(route=>`<li><code>${E(route)}</code> | ${missing.has(route)?"missing":"linked"}</li>`).join("");
 const routes=A(x.routes).map(route=>`<li><a href="${E(route.routeHref)}">${E(route.title)}</a> | <code>${E(route.displayState)}</code></li>`).join("");
 const locks=Object.entries(x.safety??{}).map(([key,value])=>`<li>${E(key)}: ${E(value)}</li>`).join("");
 return`<!doctype html><html lang="en"><head><title>${E(x.title)}</title><meta name="viewport" content="width=device-width,initial-scale=1"><style>body{font-family:system-ui,-apple-system,Segoe UI,sans-serif;margin:0;padding:20px;line-height:1.4}main{max-width:980px;margin:auto}.card{border:1px solid #d7dce5;border-radius:14px;padding:16px;margin:14px 0}code{overflow-wrap:anywhere}.blocked{color:#991b1b}</style></head><body><main><p><a href="/app">App</a> / Paper App Broker Readiness Index</p><h1>${E(x.title)}</h1><p>Read-only broker readiness index for safety locks, runtime preflight, network attempt status, adapter guard, execution control, operator go/no-go, and readiness report routes.</p><p class="blocked">No route execution, no broker contact, no order submit, no retry, no reset, no account mutation.</p><section class="card"><h2>Status</h2><ul><li>Status: ${E(x.status)}</li><li>Display state: ${E(x.displayState)}</li><li>Broker readiness route count: ${E(x.summary?.brokerReadinessRouteCount)}</li><li>Required route count: ${E(x.summary?.requiredRouteCount)}</li><li>Missing required route count: ${E(x.summary?.missingRequiredRouteCount)}</li><li>Read only: ${E(x.readOnly)}</li><li>No execution controls: ${E(x.noExecutionControls)}</li></ul></section><section class="card"><h2>Required Broker Readiness Routes</h2><ul>${required}</ul></section><section class="card"><h2>Related Broker Readiness Routes</h2><p>Broker Readiness Route Links</p><ul>${routes}</ul></section><section class="card"><h2>Safety Locks</h2><ul>${locks}</ul></section></main></body></html>`;
}
