import{buildAppNavigationReadonly as nav}from"./app_navigation_readonly.mjs";
export const VERSION="paper_app_broker_readiness_index_app_screen_v1";
export const ROUTE="/app/paper-app-broker-readiness-index";
export const REQUIRED_ROUTES=Object.freeze(["/app/paper-app-safety-lock-status","/app/paper-broker-runtime-environment-preflight","/app/paper-broker-network-attempt-status","/app/paper-trade-broker-integration-preflight-stack","/app/paper-trade-broker-adapter-guard","/app/paper-trade-execution-control-stack","/app/paper-trade-operator-go-no-go","/app/paper-trade-readiness-report"]);
const S=Object.freeze({liveTradingAllowed:false,autoTradingAllowed:false,brokerExecutionAllowed:false,brokerContactAllowed:false,orderPlacementAllowed:false,orderSubmitAllowed:false,retryAllowed:false,resetAllowed:false,accountMutationAllowed:false,routeExecutionAllowed:false});
const A=v=>Array.isArray(v)?v:[],R=e=>String(e?.routeHref||e?.href||""),E=v=>String(v??"").replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;");
export function buildPaperAppBrokerReadinessIndexAppScreen({entries=null,now=new Date()}={}){
 const n=A(entries??nav({}).entries),set=new Set(n.map(R).filter(Boolean)),missingRequiredRoutes=REQUIRED_ROUTES.filter(x=>!set.has(x));
 const routes=n.filter(x=>R(x).startsWith("/app/")&&/paper|broker|preflight|adapter|execution|readiness|operator|safety|lock/i.test([x.id,x.title,x.category,R(x),x.displayState].join(" "))).map(x=>({id:String(x.id??""),title:String(x.title??x.id??""),routeHref:R(x),displayState:String(x.displayState??"")}));
 const checks={requiredRoutesLinked:missingRequiredRoutes.length===0,brokerReadinessRoutesPresent:routes.length>=REQUIRED_ROUTES.length,readOnly:true,monitorOnly:true,diagnosticsOnly:true,noExecutionControls:true,noBrokerContact:true,noOrderSubmit:true,noRetry:true,noReset:true,noAccountMutation:true,allSafetyLocksClosed:Object.values(S).every(v=>v===false)};
 const ready=Object.values(checks).every(Boolean);
 return{ok:true,version:VERSION,appScreen:true,route:ROUTE,title:"Paper App Broker Readiness Index",status:ready?"paper_app_broker_readiness_index_ready_readonly":"paper_app_broker_readiness_index_incomplete_readonly",displayState:ready?"PAPER_APP_BROKER_READINESS_INDEX_READY_READONLY":"PAPER_APP_BROKER_READINESS_INDEX_INCOMPLETE_READONLY",ts:now.toISOString(),readOnly:true,monitorOnly:true,diagnosticsOnly:true,noExecutionControls:true,noResetControls:true,safety:{...S},checks,summary:{totalNavigationEntries:n.length,brokerReadinessRouteCount:routes.length,requiredRouteCount:REQUIRED_ROUTES.length,missingRequiredRouteCount:missingRequiredRoutes.length},missingRequiredRoutes,routes};
}
export function renderPaperAppBrokerReadinessIndexAppScreenHtml(input={}){
 const x=input?.version===VERSION?input:buildPaperAppBrokerReadinessIndexAppScreen(input);
 return`<!doctype html><html><head><title>${E(x.title)}</title><meta name="viewport" content="width=device-width,initial-scale=1"></head><body><h1>${E(x.title)}</h1><p>Read-only broker readiness index for safety locks, runtime preflight, network attempt status, adapter guard, execution control, operator go/no-go, and readiness report routes.</p><p>No route execution, no broker contact, no order submit, no retry, no reset, no account mutation.</p><ul><li>Status: ${E(x.status)}</li><li>Display state: ${E(x.displayState)}</li><li>Broker readiness route count: ${E(x.summary?.brokerReadinessRouteCount)}</li><li>Missing required route count: ${E(x.summary?.missingRequiredRouteCount)}</li><li>Read only: ${E(x.readOnly)}</li><li>No execution controls: ${E(x.noExecutionControls)}</li></ul></body></html>`;
}
